### ISSUE TITLE
Arreglos V-1.0

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#14]
Si te logueas al sistema con un usuario de juzgado solo se deberán mostrar las cámaras para la autoridad de juzgamiento que tiene ese usuario.

**Comment by mpgarcia** [comment]
•	Se actualizo a la versión 1.2.0.
•	Se modificó el código para poder hacer una sola programación del código y funcione en todos los ambientes (interno, externo, pre productivo y productivo).
•	Se corrigió el problema al acceder al panel de validación de infracciones gracias al primer punto.
•	No deja borrar una Autoridad que se encuentra en uso por algún usuario.
•	Se muestran solamente las cámaras correspondientes del Usuario que procesa videos dependiendo de la Autoridad que utiliza.
•	Se agrego un panel de Cámaras para el usuario Administrador, el cual puede listar, buscar,  agregar, modificar y/o borrarlas.
•	Se corrigieron bug menores como alerta al no escribir usuario o contraseña, mostrar cuadro de espera al procesar gps, etc.
