### ISSUE TITLE
Arreglo V-1.0

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#15]
No debe poder eliminarse una autoridad de juzgamiento mientras exista usuarios y cámaras asociadas a la misma. Cuando se borrar la autoridad sin borrar el usuario y te intentas loguear con el usuario tira cartel con el error'Problemas con el Usuario' .

**Comment by mpgarcia** [comment]
Se modifico el sistema para que no deje borrar la autoridad si existen usuarios usándola.
