### ISSUE TITLE
Sicam/versión 1.3.1/ Descarte de actas. (Testing #47)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#17]
- Se deberá achicar la letra de marca/modelo ya que hoy se muestran tres puntos suspensivos en el modelo (Adjunto imagen).
![image](https://user-images.githubusercontent.com/11543134/27288129-379548e4-54dc-11e7-9dc8-73920538e59f.png)
- Cambiar los msj cuando el acta queda en "Actas No Enviadas" por X motivo.
![image](https://user-images.githubusercontent.com/11543134/27288144-415a18aa-54dc-11e7-80fa-4135f006acd8.png)

**Comment by mpgarcia** [comment]
- Se cambio el tamaño de la fuente de 30 a 20 y se muestran hasta 20 caracteres en vez de 10.

- Se modificaron los errores del SINAI para que el cliente los vea de manera mas legible los descartes.
