### ISSUE TITLE
Sicam Estadisticas - Arreglos - Versión 1.1.

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#18]
Para usuarios de Juzgado

-El grafico de infracción semanal se cambiara por un gráfico de torta con las infracciones más comunes en los últimos 7 días. 

Para usuarios ANSV

gráfico 1: El título será 'Infracciones Procesadas por día'. Los ejes del gráfico se rotarán, siendo un gráfico de barras vertical. Las referencias serán: 'aprobaciones’ y 'descartes'.

gráfico 2: sin cambios

gráfico 3: Los ejes del gráfico se rotarán, siendo un gráfico de barras vertical. Las referencias serán: 'aprobaciones’ y 'descartes'.

gráfico 4: al pasar el mouse sobre el gráfico se muestra el nombre de la autoridad.

gráfico 5: se eliminará este gráfico-. 

gráfico 6: al pasar el mouse sobre el gráfico se muestra el nombre de la autoridad.

**Comment by mpgarcia** [comment]
JUZGADOS:
- Se cambio el gráfico de infracción semanal para que se vea un gráfico de torta del TOP 5 de infracciones.

ANSV:
- Se cambio el titulo a "Infracciones Procesadas por día" y se muestra el gráfico con barras verticales.
- El gráfico 5 se elimino.
- Se muestran el nombre de la Jurisdicción en vez del ID en los gráficos 4 y 6.

La URL de testing es la siguiente: http://ansvqa09:8080/sicam.testing.interno/stats/
