### ISSUE TITLE
SICAM/Generar Infracciones/V1.3.1 #51

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Sicam#20]
En caso de generar un infracción Domino "AS123" el DNRPA no consigue el resultado

![](https://user-images.githubusercontent.com/27014552/27962592-c1a06f7a-6308-11e7-8272-88326f2f8e23.jpg)

Cuando le damos al botón aceptar las infracciones quedan procesando

![](https://user-images.githubusercontent.com/27014552/27962620-da1e7d1c-6308-11e7-8f80-e8cb24f58aa8.jpg)
Y no se puede continuar.

**Comment by mpgarcia** [comment]
Se genero una validación del campo Dominio, debe tener entre 6 o 7 caracteres y si el servicio no encuentra el dominio genera una alerta de dominio no existente.
la url de testing es la siguiente: http://testqa09.seguridadvial.gov.ar:8080/sicam.testing.interno/
