### ISSUE TITLE
SICAM- Problema de Acceso URL- San Salvador de Jujuy - ID 17258 (*)	2/13	Siguiente	Último

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#34]
TELÉFONO CELULAR CHRISTIAN (INFORMÁTICA SS JUJUY): 388 413-4001: 

TEAM VIEWER PC 1

Usuario SSER-SICAM-CM01\SICAM
Contraseña 123456
Teamviewer 12
316346409
jujuy4600

TEAM VIEWER PC 2 

Usuario TRANSICAM01\Administrador
Contraseña 123456
Teamviewer 10
 ID 799126333
Contraseña jujuy4600

**Comment by mpgarcia** [comment]
El problema principal era que no tenian acceso a la pagina web www.java.com y por eso no terminaba de cargar el applet.
Luego habia problemas con la version de Java, habian instalado en una pc la de 64 bits en vez de 32 bits y no funcionaba en el navegador.
Quedaron las dos maquinas funcionando.
