### ISSUE TITLE
SICAM- Problema de ingreso usuarios - SANTIAGO DEL ESTERO - ID 17691 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#35]
Nos comunicaron desde Santiago del Estero (en proceso de implementación) y que están teniendo problemas para ingresar los usuarios dados de alta en la URL de SICAM (tanto en producción como en testing) en la máquina que utilizarán para procesar.
Se verifico la configuración de las maquinas y tienen los certificados cargados.
La ip fija sigue siendo la misma 190.226.45.242 
El problema de logueo es que rebota todos los usuarios (tanto en externo como en producción, se verificaron remotamente y se blanquearon las contraseñas de los usuarios).
Dejo el teléfono de contacto de Christian Cerullo que se encuentra en la jurisdicción implementando el sistema:

**Comment by mpgarcia** [comment]
Hablando con la gente de infracciones el problema que tenían era que no tienen acceso al sistema, les falta generar los usuarios asi que lo van a solucionar ellos.
