### ISSUE TITLE
Arreglos V-1.0

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#5]
*Al editar un usuario se van borrando otros usuarios( no refresca bien la pantalla).
*Al generar una infracción en el vídeo, despues al querer generar otra quedan cargadas ley/decreto e infracción de la última que se genero y el articulo vació. 
*Al aceptar/cancelar infracciones el cancelar no hace nada.

**Comment by mpgarcia** [comment]
Se arregló el problema del Listview que desaparecían los usuarios.
Se arregló el problema del Listview entre cambios de tipos de usuarios.
Se arregló el problema al crear/editar usuarios.
Se arregló el problema de recordar último ingreso en artículo e inciso.
Se arregló el problema del botón Descartes que sucedía luego de cerrar sesión.

**Comment by leoimoli** [comment]
14/07/2016
Se informo y esta del lado de testing
