### ISSUE TITLE
Arreglos Reportados por testing

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#6]
Al ingresar a la pantalla de usuarios, al ingresar en uno para editar, si luego ponemos cancelar sin hacer nada y queremos agregar uno nuevo los campos aparecen  

.Al querer agregar un usuario ya existente tira bien el msj de error pero quedan cargados los campos, CLAVE Y ID AUTORIDAD.

**Comment by mpgarcia** [comment]
Actualizado a la version 1.2.6
Se limpia el formulario al intentar crear un nuevo usuario.
Se limpian los campos Clave e ID Autoridad luego del error de usuario existente.
Se corrigió un error al pasar entre los campos del formulario con la tecla TAB.
