### ISSUE TITLE
SICAM V 1.2.9(GLPI 2032)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#7]
-Con el usuario que utiliza el municipio, en la pantalla "Seleccione la cámara" debe figuarar solamente la marca GARMIN y el modelo VERB ELITE, no permitiendo seleccionar otros. Por otro lado si selecciono la autoridad me borra los anteriores campos seleccionados (Marca-Modelo Nro. de Serie)
- Con el usuario ANSV, en la parte de infracciones en la cual se validan debe decir DESCARTAR en vez de cancelar.

**Comment by mpgarcia** [comment]
Se actualizo a la versión 1.3.0.
Se borro en la base de datos las cámaras que no correspondían.
Se corrigió un problema con la selección de marcas en cámaras.
Ahora si la marca, modelo y serie corresponde a la autoridad seleccionada quedara marcada.
Se agregó un circulo como símbolo de permiso en el sistema(verde: admin, azul: ansv, gris: municipio) y el nombre de usuario en la esquina inferior izquierda.
Se agrego un contador de Infracciones validadas o descartadas para los usuarios ansv.
