### ISSUE TITLE
Errores Reportados por testing

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sicam#9]
1) Al loguearme con un usuario ansv al ingresar en infracciones tira el msj de que el usuaria está en uso (se chequeo que no se está usando sicam arriba).  y no muestra las infracciones que se generaron.
No refresca bien las sesiones.

2) Al procesar una infracción con un usuario ansv si me deslogueo y me vuelvo a loguear el contador me sigue apareciendo con las cantidad de infracciones que procesé. (se chequeo que hay que desloguearse y darle f5 para que el contador vuelva a 0)

**Comment by mpgarcia** [comment]
1) Se borra la sesión si el usuario queda en el panel de infracciones al cerrar la sesión. Habría que hacerle un test a ver si existe otro problema adicional.
2) se borra la variable del contador al cerrar la sesión.
Ya se encuentra subido a testing.
